export const ERROR_CODES = {
  UNKNOWN_ERROR: 1000,
  AUTHENTICATION_ERROR: 2000,
  USER_MANAGEMENT_ERROR: 3000,
  HOTEL_MANAGEMENT_ERROR: 4000,
  TRANSACTION_MANAGEMENT_ERROR: 5000,

  // Authentication-specific error codes
  USER_NOT_FOUND: 2001,
  ACCOUNT_LOCKED: 2002,
  INCORRECT_CREDENTIALS: 2003,
  TOKEN_NOT_FOUND: 2004,
  FORBIDDEN: 2005,
  FAILED_CAPTCHA_VERIFICATION: 2006,

  // User management-specific error codes
  USER_ALREADY_EXISTS: 3001,
  EMAIL_ALREADY_EXISTS: 3002,
  PHONE_ALREADY_EXISTS: 3003,

  // Hotel Management-specific error codes
  HAS_ACTIVE_BOOKINGS: 4001,
  IS_LOCKED: 4002,
  CONFLICTS: 4003,
  NO_RECORDS_FOUND: 4004,
  INSUFICIENT_PERMISSIONS: 4005,
  EXTERNAL_BOOKING_ID_CONFLICT: 4006,

  // Transaction Management-specific error codes
  TRANSACTION_BAD_REQUEST: 5001,
  TRANSACTION_REFERENCE_NUMBER_CONFLICT: 5002,

  // Add other specific error codes here
};
